baseURL = 'https://alphase.netlify.app/'
languageCode = 'en-us'
title = 'ALPHASE'
theme = 'archie'

# Favicon
favicon = '/static/favicon.ico'

# Pagination
[pagination]
pagerSize = 2

# Social Tags
[[params.social]]
name = "Hardcover"
icon = "book"
url = "https://hardcover.app/@slidingsoul"

[[params.social]]
name = "MyDramaList"
icon = "list"
url = "https://mydramalist.com/profile/slidingsoul5"

[[params.social]]
name = "Letterboxd"
icon = "film"
url = "https://letterboxd.com/slidingsoul/"

[params]
  mode = "toggle"
  subtitle = "Aku ingin menjadi cukup kuat. Kemarin aku telah menjadi kuat, tetapi itu tidak cukup."
  mathjax = true
  katex = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 5