baseURL = 'https://alphase.netlify.app/'
languageCode = 'en-us'
title = 'ALPHASE'
theme = 'archie'
copyright = "Â© BuddyHeartO"

# Image Cache

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Social Tags

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:yttriumemulsion@gmail.com"

[[params.social]]
name = "Hardcover"
icon = "book"
url = "https://hardcover.app/@slidingsoul"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4